language: node_js
services:
  - docker
node_js:
  - "10.16.0"
env:
  - CYPRESS_baseUrl=http://localhost:80
cache: npm
script:
  - docker-compose pull && docker-compose up -d
  - npm run waitForServer
  - npm run cypress:run
  - npm run loadtest get_user_test.yml
  - npm run report
  - docker-compose down
before_deploy:
  - rm -f dist/index.html
  - mkdir -p dist && cp test-results.json.html dist/index.html
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: dist
    on:
      branch: master
