version: '3'

services:
  reverse-proxy:
    image: traefik:1.7.12 # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "4000:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  mongodb:
    image: mongo
  frontend:
    build: "./cloned-repos/pdes-tp-buggysoft/"
    labels:
    - traefik.frontend.rule=PathPrefix:/
  backend:
    build: "./cloned-repos/pdes-tp-backend-buggysoft/"
    environment:
    - MONGO_URL=mongodb://mongodb/pdes_tp_backend_buggysoft
    - NODE_ENV=production
    labels:
    - traefik.frontend.rule=PathPrefixStrip:/api
